### ISSUE TITLE
Improve search in the references selector

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#106]
Currently the reference selector only enables users to search for references using their title, searching by author name shoud and other attributes should also be added

**Comment by hammer** [comment]
Also how does the selector behave as the number of references scale?

**Comment by sehyod** [comment]
The selector shows only up to 5 results. From a performance point of view, I think we can keep the filter function very basic for now, and rework it later if we realise that it does not scale when working with numerous references.
