### ISSUE TITLE
Generate reference citation key for ingested references

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#112]
From #109 
> We could automatically generate a key on upload, and then allow the users to edit the key if they want. A common choice for a key is the first author's last name plus the publication year, e.g. hammerbacher1999. If there's a key collision just append a, b, c, etc. If we don't have metadata just use untitled plus 1, 2, 3, etc.

Looking at the 9 PDFs I have been using locally, Grobid only captures a date for 2 of them. I think these PDFs came from arxiv, so maybe that's part of the reason? Regardless, we'll need to improve this with the medium-term task of canonicalize references against some database.

**Comment by gjreda** [comment]
An edge here that needs a little thought: We currently don't persist the reference objects and instead just read a json-ified version of Grobid's output from disk. We need to make sure the citation keys remain consistent in case the user uploads more references (i.e. that `Untitled2` doesn't become `Untitled3`, or that `hammerbacher1999a` doesn't become `hammerbacher1999b`).

So we'll probably need to write these on disk for consistency.

**Comment by gjreda** [comment]
@sehyod @cguedes For the `a, b, c ... 1, 2, 3` piece of the citation key, do you feel it makes more sense to do that on the frontend, since the frontend will always have the reference list held in memory?

I think this might make the most sense since we want to allow users to manually change the citation key. Otherwise, we will need to persist the keys on the backend and then pass "updates" back and forth between the frontend and sidecar.

Long-term, I agree that the backend should be responsible for this piece.

**Comment by cguedes** [comment]
The frontend don't store mutable state about references. 
It makes sense that the frontend would provide some UI to rename/merge references, but should be something that is sent over to the backend for storage.

For now I think that the citation key should be managed in the backend and then we can build a UI for rename and merge.

**Comment by gjreda** [comment]
@cguedes Sounds good. I'm planning to add some very basic storage to the backend as part of #102.

**Comment by hammer** [comment]
Wow just realizing there's a whole world of people who write custom rules for citation key generation!
- [Specify custom BibTeX key formats for entire library](https://forum.paperpile.com/t/specify-custom-bibtex-key-formats-for-entire-library/30) on the Paperpile Discourse
- [Customize the BibTeX key generator](https://docs.jabref.org/v/v4/setup/bibtexkeypatterns) in the JabRef docs

We may need to file a follow up issue (not for the MLP!) to allow the rules we use here to be customized...
