### ISSUE TITLE
Ability to display Reference ingestion status

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#113]
From #109 

> The ingestion pipeline should display more complete information about its status while running, and we need to display information about how references have been processed after the ingest pipeline has finished, e.g. the PDF is available in the local project directory, metadata was parsed successfully from GROBID, content has been extracted and made available for AI interactions, etc.

**Comment by hammer** [comment]
I probably shouldn't have combined those two into a bullet, as they are pretty different in implementation. The first request is about references that are being processed, and the second request is about the reference list once processing is done.

**Comment by gjreda** [comment]
Some thoughts on the "states" a Reference can be in. Naming conventions are off the top of my head, so feel free to suggest others!

1. `staged_for_ingest` - Uploaded and ready for Grobid parsing, but Grobid parsing not yet attempted.
2. `grobid_processed` - Grobid parsing was attempted and ran successfully. This state does not aim to tell us specifics about what metadata was extracted.
3. `grobid_failure` - Grobid parsing was attempted and failed. Grobid does not tell us much about why a PDF failed, so there's not much we can say here.
4. `available_for_chat` - Reference content has been extracted and will be used as part of `chat`.

In the future, I imagine that we'll have additional statuses, but I don't think we should solve for these now as we do not yet have ingest pieces for them.

**Comment by gjreda** [comment]
Dropping notes from Slack thread with @cguedes and @sehyod

1. Update IngestResponse to include a status for each Reference - that the current Reference payload at the end of ingest should also include a status
2. Add a new endpoint to retrieve all References that have previously been processed (these are just stored as json on the filesystem, so y'all might just be able to fetch them as well).
3. Add a new endpoint to do a status check on References during ingestion, with the intention that this would be called while the full ingestion pipeline is running, so that the UI can update as necessary.

> generally yes. The idea is the be able to initiate an ingestion process (1) and get status for the background processing (3) by calling a different endpoint (bc the first call needs to keep running for the ingestion). The (2) is an extra safeguard we can run when the app starts but not really needed for now IMO.

> For (1) I think that you won’t be able to return the references information before the processing finish so we can implement (2) to get all references with each ref containing the current processing status. And (3) to check if there is any pending action in progress with a lightweight and specialised payload.
