### ISSUE TITLE
Transparent text should not be allowed in the editor

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#115]
From #110 
> New issue I encountered today: if I select all on the text in an editor window and then paste text over it, the editor window appears blank, but the text content is there, as it can be highlighted and shows up in the AI interactions window as selected text. Video below.

This issue only occurs when pasting text from the PDF viewer. What actually happens is that the PDF Viewer renders PDFs as images and then add transparent text on top of the image to make it selectable. When pasting the text in the editor, formatting is preserved, making the text invisible in the editor.

I think we want to preserve text formatting when pasting, but we can add a rule that removes transparent color property as I don't see any use case where users would actually want to paste transparent text

**Comment by sehyod** [comment]
After discussing this with @sergioramos, it appears we usually both use Cmd+Shift+V in editors to paste without formatting. What do you think should be the behaviour of the editor here @hammer? Do we want to preserve formatting at all?

**Comment by hammer** [comment]
It's definitely tricky, I see at least 3 options:
1. Paste with source style
2. Paste and match destination style
3. Paste with no style

I suspect we should support all 3, with 2 possibly the default. I think 1 is often the default but is usually annoying. I think Notion does 2 by default.

Should we change the title of this issue to be a larger referendum on paste styling? I don't want to get too crazy right now on the larger problem as I'm sure it's a bit tricky and will require a significant test suite.

For the particular case of copying and pasting out of the PDF reader, I do think disabling the `transparent` property is the right thing to do, as it was definitely unexpected for me!

**Comment by hammer** [comment]
We

**Comment by hammer** [comment]
I think I accidentally re-opened this when browsing on mobile, sorry about that!
