### ISSUE TITLE
Drag and drop PDF takes over editor with no way out

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#118]
Drag and Drop a PDF onto the "RS" logo or the "Explorer" file view (I think anywhere other than the sanctioned "upload" box in the references panel).

The window turns into a PDF viewer and there's no way to get back to the RefStudio app other than closing it and re-opening.

We should either `preventDefault` on all drag-and-drop interactions in the Tauri window or allow PDFs to be dropped anywhere to import them.

**Comment by hammer** [comment]
My preference is to allow PDFs to be dropped anywhere. I've seen other apps handle this situation when a PDF is dragged over app window by graying or blurring the app and displaying a message like "Add PDF to references" or something like that.
