### ISSUE TITLE
References component MVP

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#12]
Let's get @gjreda a simple drag and drop and/or file browser so he can start ingesting PDFs from the UI and kicking the tires on the Tauri sidecar architecture.

**Comment by hammer** [comment]
@sergioramos notes https://github.com/transloadit/uppy could be useful

**Comment by gjreda** [comment]
Building on @hammer's point though, I'd love to get the mechanics of the PDF ingestion UI in place since the sidecar pattern - getting Python working in Tauri - is an uncertainty for me. I imagine once we have a prototype of the sidecar pattern in place I'll be able to iterate on it pretty smoothly.

**Comment by denjell-crabnebula** [comment]
You might like to check out what the folks over at openbb are doing for their python needs:

https://github.com/OpenBB-finance/pywry

**Comment by hammer** [comment]
@denjell-crabnebula thanks for sharing! It would be interesting to hear how pywry fits into the overall application architecture. We were planning on putting our Python code into a sidecar. Would you recommend pywry instead?

**Comment by cguedes** [comment]
I think that #49 will fix this issue by listing uploaded references, listing them in the editor (@ trigger) and also by adding to the document with a click in the references list.

Agree @sehyod ?

**Comment by sehyod** [comment]
Yes, #49 and this issue are related. We can close both once the PR for #49 is accepted and merged

**Comment by cguedes** [comment]
Closing as #81 is merged.
