### ISSUE TITLE
Content doubles after copy and paste in text editor

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#121]
Steps to reproduce:

1. Open Ref Studio
2. Open `file 1.tiptap`
3. Select all
4. Paste
5. Open `file 2.tiptap`
6. Navigate back to `file 1.tiptap`

Now content on `file 1.tiptap` has been duplicated!

I suspect there's some simple state management fix that's already in the works but figured I'd file the bug anyways.

Video:
https://github.com/refstudio/refstudio/assets/15233/f08dcc48-5dba-4397-849c-69934cb5a146

**Comment by hammer** [comment]
Yep just tested with https://github.com/refstudio/refstudio/pull/105 and this behavior is fixed

**Comment by cguedes** [comment]
I confirm that it was a known issue and that #105 aimed to also fix that.
