### ISSUE TITLE
Find replacement for dataclasses-jsonschema

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#136]
https://github.com/refstudio/refstudio/pull/126 added a dependency on https://github.com/s-knibbs/dataclasses-jsonschema, which is in maintenance mode. @gjreda already hit an issue where the new `T | None` syntax for optional types is not handled by `dataclasses-jsonschema`: https://github.com/refstudio/refstudio/pull/135.

While I like the idea of pulling Python types into JavaScript, I think it's a nice to have and not a must have at this stage of the project, and I'm nervous about hitting more issues due to this dependency.

I don't want to spend much time on it but if we could either find a replacement for this dependency or remove it, I think that would allow us to stay focused on features on the critical path for the project right now.

**Comment by gjreda** [comment]
We should be able to switch to Pydantic pretty easily and it will generate jsonschema for us: https://docs.pydantic.dev/latest/usage/schema/
