### ISSUE TITLE
Add source Reference metadata to Chat response

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#143]
A Chat response currently only includes the message text. Ideally, we'd like to cite the References that were used to create the message response.

We should update the response to include metadata about the source References.

- [x] Update ingest to use `pypdf` for text extraction on _all_ PDFs so that text for grobid success/fails are parsed in a consistent way. This will allow us to also include page numbers on our Reference metadata.
- [x] Add page number to `Chunk` metadata
- [x] Add reference metadata [to ranker context here](https://github.com/refstudio/refstudio/blob/main/python/sidecar/ranker.py#L18) so that our ranker query returns appropriate metadata
- [x] Update chat to include relevant reference metadata in in prompt
- [x] Update LLM response to include citations of appropriate references (might need to play around with LLM prompt)
- [x] Update CLI params to allow for `n_choices` to be utilized
- [ ] Update python/readme.md

**Comment by shauryr** [comment]
if we decide to use langchain they have a method to do that - https://python.langchain.com/docs/modules/chains/popular/vector_db_qa#return-source-documents 

If we want to keep it simple we can just use prompting to cite the article like I did in S2QA where the source is send to the LLM as context and it cites it in the generation.

**Comment by gjreda** [comment]
@shauryr yea, I was thinking something like the latter where we include the citations in the response from the LLM. I did similar when building a [very early prototype](https://github.com/gjreda/scratch-pdf-bot/tree/main).

**Comment by gjreda** [comment]
As part of this we might want to update ingest to use text extracted via a pdf parser (e.g. `pypdf`) rather than the document text received from the Grobid response. Using the text extraction via our PDF parser will also allow us to add `page_number` to the metadata for a given `chunk`, which will be useful for informing a user how the chat bot came up with an answer.

**Comment by gjreda** [comment]
Poking around LlamaIndex's QueryCitationEngine, it looks like it accomplishes adding citations by:
1. Some prompt-fu [here](https://github.com/jerryjliu/llama_index/blob/c29e812e6161d7c7ce0b6cd069680eaa0b994113/llama_index/query_engine/citation_query_engine.py#L22)
2. Adding a list of [citation source nodes to the response](https://github.com/jerryjliu/llama_index/blob/c29e812e6161d7c7ce0b6cd069680eaa0b994113/llama_index/query_engine/citation_query_engine.py#L187) which are able to be drilled into more deeply so that a user can see the underlying text chunk (see [example here](https://github.com/jerryjliu/llama_index/blob/c29e812e6161d7c7ce0b6cd069680eaa0b994113/docs/examples/query_engine/citation_query_engine.ipynb))
