### ISSUE TITLE
Allow for files to be created, saved, opened, and deleted in the editor

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#157]
Standard file lifecycle. Probably export too?

---

Edited by @sehyod:
Here are the subtasks for this tickets:

- [x] #197
- [x] #209
- [x] #212
- [x] #213
- [x] #214

This brings up the question of how to integrate these actions into the UI.
New file, Save and Export can all be added to a File menu on the top
Delete and Rename are trickier: the two entry points I can see for them are:

selecting a file in the explorer and pressing a keyboard shortcut (respectively F2 and Cmd+Backspace)
implementing a context menu

**Comment by sehyod** [comment]
Closing this issue because all subtasks have been completed
