### ISSUE TITLE
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead.

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#158]
This warning pops up a bunch when I run `yarn test`:

```
$ yarn test
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Here's the linked doc: https://reactjs.org/link/switch-to-createroot

**Comment by cguedes** [comment]
@sehyod I think this was introduced by the addition of `@testing-library/react-hooks` (so that we can use `waitForNextUpdate`. 

Will check into more detail into this later.
