### ISSUE TITLE
Switching editors reloads PDF in other pane

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#162]
If you have two editors and a PDF open, you can toggle back and forth between the two editors and see the PDF visibly reload:

https://github.com/refstudio/refstudio/assets/98301/b8381773-58c8-4f25-acb6-6259b37ea51c

The green links linger as it reloads, which is a bit jarring. You also lose your scroll state in the PDF. This may indicate that we're re-rendering a component when we should not be.

**Comment by danvk** [comment]
Possibly the same bug, resizing the window also causes the PDF to flicker as it reloads:

https://github.com/refstudio/refstudio/assets/98301/a393ad96-0645-44e6-87c1-59066b96cc11

Sometimes "Loading Page…" appears many times during this sequence, other times just once:
<img width="957" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/0dfc8312-7b64-401b-af63-4bb5e9dec74e">

It might be better to show the "Loading…" indicator only after some amount of time has passed (say 500ms) to avoid unnecessarily jarring transitions when everything happens quickly.

**Comment by hammer** [comment]
@cguedes @sehyod what do y'all think of this one? I wanted to hold off on mentioning it as I know we've been revisiting the architecture of the editor area to allow for other kinds of content beyond text editing and PDF reading, but I still have this issue and it's a bit distracting. Is it an easy fix?
