### ISSUE TITLE
Notion parity

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#168]
> From @danvk at https://github.com/refstudio/refstudio/pull/154#issuecomment-1593557137:
> 
> A few remaining differences I noticed from Notion, probably not all related to this PR:
> 
> 
> - [x] Typing should hide the drag handle until you move the mouse again
> - [x] When you create a fold by typing <kbd>></kbd> at the start of a line, it should be open by default.
> 
> - [ ] When you type <kbd>></kbd> at the start of a bulleted list item, it shifts down to the next line rather than turning the list item into a fold as Notion does:
> 
> https://github.com/refstudio/refstudio/assets/98301/edfd3f0f-9cef-4d64-ace1-36ee3c17c8d8
> 
> - [x] When you hit <kbd>Enter</kbd> at the end or the middle of a list item, it should add a new list item, rather than an item outside the list.
> 
> https://github.com/refstudio/refstudio/assets/98301/137e1016-ba42-4986-9c96-8c797c6817e4
> 
> - [ ] Backspacing over the "•" at the start of a bulleted list item should remove that item the bulleted list (or move it onto the previous item in the bulleted list if it's not empty):
> 
> https://github.com/refstudio/refstudio/assets/98301/5240a72b-7690-4250-a215-5d678c22d871
> 
> - [x] In Notion, the content under a fold isn't indented. Only the fold caret itself is:
> <img width="623" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/70c8cc7f-9378-4a9e-8ec9-7e32f522a1a5">
> 
> vs. in RefStudio the content _and_ the caret are indented:
> <img width="408" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/5e596c82-b443-48fe-988f-483132b63e66">
> 
> - [ ] When you select text, there are broken rectangles for lines that aren't completely selected (the blue under "Ite" on the first line):
> <img width="356" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/3c27c235-51a0-4956-9e6a-fb9c9ebb3745">
> 
> Notion just selects the text, rather than the full width of the editor for each line. This looks neater.
> 
> - [x] Typing `## heading<enter>` leaves you in H2 style in RefStudio whereas it drops you back into paragraph style in Notion (which is the better behavior).
> 
> - [ ] Selecting three lines of text and clicking the "Bulleted List" button in the toolbar should make a bulleted list with three items (it currently does nothing).
> 
> _Originally posted by @danvk in https://github.com/refstudio/refstudio/issues/154#issuecomment-1593557137_

**Comment by hammer** [comment]
To expand on the last point related to unordered lists, it feels like lists in general are not working correctly. In both unordered and ordered lists, hitting enter when the cursor is at the end of a list item does not add a new item, and in come cases it actually deletes content. For example, on the default `file1.tiptap`:

https://github.com/refstudio/refstudio/assets/15233/5b34a26a-1575-42da-b16c-817504a5d99b

**Comment by danvk** [comment]
My guess is that the `<draggable-block>` wrappers are the root issue behind both lists not working and the odd-looking selections. If you visit https://tiptap.dev/examples/default, for example, these both work the way I'd expect:

https://github.com/refstudio/refstudio/assets/98301/4140a110-f904-45dd-8ce0-3c391b46017c

**Comment by sehyod** [comment]
Closing this issue since the remaining tasks have been split into smaller issues: #327, #328, #329, #330 and #332
