### ISSUE TITLE
Testing node manipulation

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#169]
From @danvk at https://github.com/refstudio/refstudio/pull/154#pullrequestreview-1482196425:

> The code for manipulating the nodes is quite intricate and my main question is around how we want to set up testing for it. A few ideas:
> 
> - Have a "script" that a human periodically goes through ("type ABC, put the cursor between B and C and hit enter"). This would be tedious but would at least document our expectations. This is kind of what @hammer and I are doing already in the comments :)
> - Look into some kind of test runner like [Playwright](https://playwright.dev/). These sorts of things are always a bit of a PITA to set up but they do create an extremely realistic test environment. I believe this is what VS Code uses. TipTap looks like it [uses Cypress](https://github.com/ueberdosis/tiptap/blob/develop/tests/cypress/integration/core/extendMarkRange.spec.ts), which is similar.
> - Try to create some sort of unit test by creating the nodes that tip tap expects (maybe by writing out Markdown) and calling the individual functions like setCollapsibleBlock with each situation (no selection, selected text on the fold header line, selection crossing the header line and foldable content). Depending on how TipTap works internally, this may or may not be possible

**Comment by sehyod** [comment]
Because the PR (#154) was not blocking for other features, we took the time to add tests before merging it.
We did it the third way: extracted the logic in functions and then wrote unit tests for these functions. We reached a coverage of almost 100% for them
I think we can close this issue, unless you want to keep it open to add other tests, like, for example, with Playwright.

**Comment by hammer** [comment]
@sehyod let's wait to see what @danvk thinks of the testing we have in place before closing

**Comment by danvk** [comment]
The testing approach from #154 looks great. My one suggestion (implemented in #186) is to make the tests more legible by making both the input state and output state more "visual".
