### ISSUE TITLE
Extract raw PDF text even if Grobid parsing fails

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#175]
We do not currently attempt to extract PDF text if Grobid parsing is unsuccessful. We can still do this via something like `pdfminer`, which would allow us to make the Reference content available for chat.

**Comment by hammer** [comment]
Linking back to an old issue where we listed some options for PDF parsing for my own convenience: https://github.com/refstudio/refstudio/issues/14

**Comment by gjreda** [comment]
Using `pypdf` for this as simple text extraction is much easier with it than it is with `pdfplumber`. `pypdf` is also what's used under the hood in both LangChain and LlamaIndex.

`pdfplumber` seems better suited if we wanted to go deep in the weeds on pdf parsing and roll our own logic, rather than simply extracting the text out. See [this discussion](https://github.com/jsvine/pdfplumber/issues/242) as an example.
