### ISSUE TITLE
Add sidecar endpoint so UI can pass Reference metadata updates to backend

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#182]

**Comment by gjreda** [comment]
@cguedes When I added this earlier, I assumed y'all would pass in the full Reference as json and I would update everything on the backend ([see here](https://github.com/refstudio/refstudio/blob/main/python/sidecar/storage.py#L55)).

Two questions:
1. Are there better input params for y'all? For example, maybe a structure like:
```json
[
  {
	"source_filename": "example.pdf",
	"updates": {
	  "field_to_update": "value"
	},
  },
  {
	"source_filename": "another_example.pdf",
	"updates": {
	  "authors": [
		{"first_name": "John"},
		{"surname": "Smith"}
	  ]
	}
  }
]  
```
2. What would you want to get back in the response? I'm thinking just `{"status": "ok"}` or `{"status": "error"}` if the update failed for some reason. I'm assuming you would not a response of the updated metadata since you were the provider of it.

**Comment by cguedes** [comment]
Sure, the full reference as json would be too much.

1. I like it if the updates fields (i.e. field_to_update) is a member of a ReferencePatch type. We then need to understand how to reset values (i.e. make then undefined). Maybe we can't do that and instead only make them an empty string. 

2. A status ok/error is good. Would be interesting to get error details if you can have them.
