### ISSUE TITLE
"List view" of many references in left sidebar

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#202]
> "List view" of many references in left sidebar: list view with sort, filter, add, export functionality at the top

From #159 

This can be implemented like the following image:

- Add and export actions in the panel actions (right icons)
- Sort in a menu triggered by the rightmost icon (3 vertical dots)
- Filter by typing in the text area

<img width="543" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/657583fd-fd5a-4c71-9d2c-e38e8ab4b830">

@hammer how do you see the export functionality? Should we download a .bib file?

**Comment by hammer** [comment]
Export to .bib is definitely the first place to start! No worries if we just put a no op export button there for now if it’s hard
