### ISSUE TITLE
Set max-width on tabs

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#228]
A single paper with a long name can take up the entire editor width, especially if you have a split-screen view:
<img width="1448" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/064d8c0e-0eba-4ce3-bbe9-1e6242fea14a">

This prevents seeing other tabs (including the active one in this screenshot).
Additionally, you can't click the "close" button if it's offscreen on the right.

Setting a max-width on tabs would help here. 

Using VS Code as a model, they show the file name and an abbreviated path. They also have a very small horizontal scroll bar to handle overflow:

<img width="835" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/888ae2d1-df32-49b8-99d5-498b1f66418c">

**Comment by hammer** [comment]
@sehyod I believe this was implemented with the new design?

**Comment by sehyod** [comment]
You are right, this has been implemented in #370. I am closing this issue
