### ISSUE TITLE
Add knip to pre-push hook

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#258]
We have added knip to the CI in #225 
We should also add it to our pre-push hooks

**Comment by sehyod** [comment]
@cguedes @danvk I'm opening this issue because I just had a failing CI job on a PR because of an unused file. This is really nice but I think it would make sense to run `knip` along our other pre-push hooks to catch the error before pushing the code.
I don't think the command takes too much time, so it should be fine to run it on pre-push. Let me know if you think of any reason why we shouldn't

**Comment by danvk** [comment]
@sehyod sounds good to me!
