### ISSUE TITLE
Update tauri bundle identifier

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#261]
We're still using the Tauri defaults:

https://github.com/refstudio/refstudio/blob/ed6880d3e6de54f5908b1800bf0e57eea0e4eb7e/src-tauri/tauri.conf.json#L45

ideally this would be something like `com.refstudio` or `studio.ref` or anything that we control. Since we store all files in a directory that includes this identifier, changing this would be like doing a data reset for everyone.

**Comment by cguedes** [comment]
Agree. What should we use @hammer?

**Comment by hammer** [comment]
@cguedes we own ref.studio. Should we use that or is it advisable to put a subdomain onto it?

**Comment by cguedes** [comment]
I think we should have a subdomain (app.ref.studio) there like: `studio.ref.app` so that we don't "use" the `ref.studio` for this.

Related [discussion](https://github.com/tauri-apps/tauri/discussions/5976) about this topic.
