### ISSUE TITLE
Add a button to use rewrite suggestion in the editor

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#269]

**Comment by cguedes** [comment]
@sehyod What do you think of having this button (action) in the "Rewrite" and the "Chat reply".

**Comment by sehyod** [comment]
Yes, we can do that!
However I think it could be done in another PR (maybe related to #270). Because instead of just replacing the text, we could use the references returned by the backend, and replace them with proper reference nodes in the editor
