### ISSUE TITLE
Lots of warnings when switching between tabs in the editor

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#276]
I'm getting this error a lot when I switch tabs in the editor:

> Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.

Here's a video:

https://github.com/refstudio/refstudio/assets/15233/5e4c129f-fdad-478c-9dee-50a13197a29a

**Comment by sehyod** [comment]
This is a bug that comes from TipTap, but a PR has recently been merged to fix it (https://github.com/ueberdosis/tiptap/pull/4000) As mentioned in [this comment](https://github.com/refstudio/refstudio/pull/267#discussion_r1258593459), I think we should not automatically open the drawer when an error notification is received, at least for now

**Comment by hammer** [comment]
It looks like this fix is in https://github.com/ueberdosis/tiptap/releases/tag/v2.1.0, released 3 weeks ago. Should we bump our version up to get the fix?

**Comment by sehyod** [comment]
Great! I had not realized they had released it. We should definitely adopt the new version
