### ISSUE TITLE
View PDF files inline

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#28]
@cguedes mentioned he's interested in exploring our options for adding PDF viewing.

As mentioned in last week's sync meeting, https://github.com/allenai/pdf-component-library is a library from AI2 built on https://github.com/wojtekmaj/react-pdf that may be useful for us. I believe this library is used in their [Semantic Reader](https://www.semanticscholar.org/product/semantic-reader) project.

**Comment by cguedes** [comment]
This was closed by #31
