### ISSUE TITLE
[Frontend] Rewrite choices

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#281]
Improve the UI having (Add Rewrite parameters for n_choices and temperature #275) implemented for the backend.

The current UI (see image below) only displays one rewrite option. We should improve to provide 3 options for the rewrite.

![Screenshot 2023-07-11 at 16 43 39](https://github.com/refstudio/refstudio/assets/174127/f5f3c6e4-5413-4f00-8911-c2cfc025dc11)

**Comment by gjreda** [comment]
We'll generally want to keep the temperature in the regions around 0.7 and 0.9

**Comment by cguedes** [comment]
> We'll generally want to keep the temperature in the regions around 0.7 and 0.9

Ok. @hammer do you think that this should also be configurable in the UI?

Also, speaking about temperature and manner configurations, do you think it makes sense to have them in the settings modal to be configured globally (and by default if we implement a UI when executing the specific command for AI interaction)?
