### ISSUE TITLE
Build a macOS bundle

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#311]
https://tauri.app/v1/guides/building/macos

I think we need to put a `.app` file inside of a `.dmg` file but I'm not sure exactly. Either way it would be nice for people to install the app without having to clone the repo.

**Comment by cguedes** [comment]
@hammer what do you think of creating [github releases](https://github.com/refstudio/refstudio/releases/new) (with a version tag) for the `.dmg` files? There, we can also add some extra guidance on breaking changes, installation notes, etc...

**Comment by hammer** [comment]
For sure will need to version these artifacts. How do people feel about semver vs time-based release names these days? Everyone was moving towards the latter last I checked…

**Comment by cguedes** [comment]
Honestly I think it’s fine to use semver for now, and start with a 0.1.0 release (we can have breaking changes in 0.2.0). Otherwise we will need to figure out names for every release. But I’m not familiar with that naming convention

**Comment by hammer** [comment]
The alternative to semver is calver, it's not that complicated: https://calver.org. I actually prefer a hybrid such as the one used by Cockroach Labs (https://www.cockroachlabs.com/blog/calendar-versioning/), so let's call the first release 23.1.0.

**Comment by cguedes** [comment]
I like that calendar version convention. So the next release would be just `23.2.0` bc is the second we have for 2023?

**Comment by hammer** [comment]
Right or 23.1.1 if it were a patch/bugfix release

**Comment by cguedes** [comment]
Perfect 👍 will adopt that rule for the PR and add guidelines to the README
