### ISSUE TITLE
Document project storage directory layout and behavior

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#317]
If we're going to make project storage configurable (https://github.com/refstudio/refstudio/issues/286) and add project lifecycle interactions (https://github.com/refstudio/refstudio/issues/288), it will be beneficial to document how these directories and files are managed by the app, including behavior when the directory already exists and has stuff in it.

**Comment by cguedes** [comment]
@hammer I've document the behaviour in the PR (#350) that implements #286 and #288. Should we have it elsewhere?
