### ISSUE TITLE
Improve TipTap editor content replacement

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#32]
We need to add a delay (setTimeout) in order to prevent a weir behaviour in the TipTap editor when we try to change the content (i.e. toggle files).

We should investigate a way to fix this. Maybe this issue won't exist if we move the TipTap editor instance to the redux store.

_Originally posted by @sehyod in https://github.com/refstudio/refstudio/pull/30#discussion_r1204476574_

**Comment by cguedes** [comment]
We still need to move the file content to a Jotai store to evaluate if the TipTap integration can be fixed. What do you think @sehyod?

**Comment by sehyod** [comment]
I agree, we should move the file content to a jotai store so that we don't have to re-read a file every time we select it anyway. Hopefully this will fix the content replacement bug at the same time
