### ISSUE TITLE
Update grobid ingest to only parse header data rather than full text

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#349]
@shauryr called this out in #111

**Comment by shauryr** [comment]
Is this the line which needs to be changed? `processFulltextDocument` to `processHeaderDocument` as mention [here](https://github.com/kermitt2/grobid_client_python) 

https://github.com/refstudio/refstudio/blob/af4e0b368c75c38a09b92033cacd270931b90463/python/sidecar/ingest.py#L222

**Comment by gjreda** [comment]
@shauryr yep, that should be the only change needed here!
