### ISSUE TITLE
Design for Welcome Screen

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#369]

**Comment by cguedes** [comment]
@sehyod you can also configure the app logo in the scope of this task.

You just need to download this file to any path and the run the following:

`yarn tauri icon <path-to-the-file>/Mac.png`

![Mac](https://github.com/refstudio/refstudio/assets/174127/5e3f658a-88d6-486c-a721-7503a302839f)

----

In preparation for the web version, I think that you can also update the `index.html` with the favicon using the following image and [this tool to create the required images](https://favicon.io/favicon-converter/):

![Windows Icon](https://github.com/refstudio/refstudio/assets/174127/bb9bad08-2158-4718-9dd9-7d098e12c875)



**Note:** Both images were created by the design team and are available for download in Figma.
