### ISSUE TITLE
Design for Reference Details Editor

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#377]
Design proposal

![image](https://github.com/refstudio/refstudio/assets/174127/cbab412d-ecd3-41e7-8c93-d96f01bab1e9)

**Comment by hammer** [comment]
We discussed in our meeting last week that it may make sense to seek reference details and the PDF reader separate. Let's continue that conversation here this week!

**Comment by sehyod** [comment]
I think we can update the reference details view to include the PDF file (for references that have been uploaded through RefStudio), and keep the PDF viewer to open pdf files from the explorer.

So we would have 3 different views:
 - Reference details table and PDF viewer for RefStudio references
 - Reference details table only for references that have been added with Semantic Scholar
 - PDF viewer only for any pdf file opened from the file explorer

I think it would also be very interesting to see how users use the tool to make a decision here. Maybe the individual details table is not that useful given that everything is already available in the table with all references?

**Comment by hammer** [comment]
I don't think it's a good idea to have different reference detail views when we do and do not have a PDF. I think we need 2 separate views: 1 PDF reader, and 1 reference detail view. We should make it easy to open the PDF reader view from the reference detail view if the PDF is available.

**Comment by sehyod** [comment]
That makes sense. We could add a row to the details table for the corresponding file name (when available), as an hyperlink to open the PDF.
