### ISSUE TITLE
Show unsaved files in Explorer

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#405]
When you have an unsaved file ("Untitled-2"), it doesn't show up in the Explorer list on the left:
<img width="779" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/b963a8f2-235b-4dff-8705-18b7196061e8">

Once you save, it does:
<img width="774" alt="image" src="https://github.com/refstudio/refstudio/assets/98301/634047e8-fc69-4a35-94e5-7e4428a5eb1f">

The unsaved file should appear in the list before it's saved.

**Comment by cguedes** [comment]
We never had that as a feature. And I think it makes sense the way it’s implemented.

**Comment by sehyod** [comment]
I agree with Carlos, I think the explorer should only contain actual files. And VSCode does the same

**Comment by hammer** [comment]
Will close this one as won't fix for now and see if users think it's weird.
