### ISSUE TITLE
Use the Python HTTP API from Tauri 

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#406]
We currently communicate from TypeScript <-> Python using a [sidecar process](https://tauri.app/v1/guides/building/sidecar/). We start a new process whenever we need to communicate. data is sent to Python as a JSON command-line argument and we read JSON back from stdout.

With the web version of RefStudio (#347) we have an HTTP server. This means that the web version and the desktop version have two different ways of communicating. Ideally we'd make the desktop app use the HTTP server as well so that we can unify these code paths.

See @hammer's comment here for some context: https://github.com/refstudio/refstudio/issues/17#issuecomment-1563288836

The simplest path forward is to use `Command` to spawn the web server and then Tauri's version of [fetch](https://tauri.app/v1/api/js/http#fetch) to communicate with it.

**Comment by cguedes** [comment]
@danvk great work in #407. Exited to see how we can take advantage of this server and implement a single workflow for the desktop and web.

**Comment by gjreda** [comment]
fixed by #425 and #442
