### ISSUE TITLE
Improve the projects API (output payload and types)

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#414]
This is a follow-up after https://github.com/refstudio/refstudio/pull/393#pullrequestreview-1593894064

We should also make sure we can configure a project name.

CC @danvk

**Comment by danvk** [comment]
FastAPI generates OpenAPI JSONSchema here: https://fastapi.tiangolo.com/tr/tutorial/first-steps/#openapi

You can see it for our various APIs here:
http://127.0.0.1:8000/api/sidecar/openapi.json

It can be generated programmatically using this recipe: https://github.com/tiangolo/fastapi/issues/1173#issuecomment-605664503

**Comment by gjreda** [comment]
@cguedes I think this done now?

**Comment by cguedes** [comment]
Yes, this is done.
