### ISSUE TITLE
Break up http.py

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#415]
This has grown quite large and should be broken up into submodules

**Comment by gjreda** [comment]
@cguedes I'm planning to restructure the backend and roughly follow [this template](https://github.com/zhanymkanov/fastapi-best-practices), grouping things by domain. So we'll have something like the following:
```
sidecar/
    config.py --> config-related stuff from what is now called settings.py
    main.py
    web.py
    search/
        router.py --> definition of endpoints, stuff that is now in http.py
        schemas.py --> definition of search-related types, from typing.py
        service.py --> business logic sort of code, stuff that now lives in search.py
    projects/
        router.py --> endpoints from http.py
        schemas.py
        services.py
    references/ --> i'll probably rename `ingest` related logic to `references`, since that's the endpoint prefix we use
        ....
....
```
This pattern largely mirrors what Netflix does for [Dispatch](https://github.com/Netflix/dispatch/tree/master). I think it'll be nice to have as other domains of the application get built out, and also as existing areas like `ai` get more depth to them.

Let me know what you think.

**Comment by gjreda** [comment]
Gives us some nice organization to the swagger docs too
<img width="1224" alt="image" src="https://github.com/refstudio/refstudio/assets/921995/099ea0f5-292a-43ec-b7fc-8bbc9a36a001">

**Comment by cguedes** [comment]
I like this a lot. 💪
