### ISSUE TITLE
Log the full path of an HTTP request

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#424]
We should log the entire path of an HTTP request instead of the path configured for each FastAPI instance.

<img width="532" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/f596f795-5058-4eff-bd1d-ef29106ecd03">

![image](https://github.com/refstudio/refstudio/assets/174127/8d808757-b644-4a59-a016-7465c14307f9)

CC @gjreda

**Comment by gjreda** [comment]
@cguedes This is caused by an issue in one of the dependencies upstream
- https://github.com/encode/starlette/issues/1336
- https://github.com/tiangolo/fastapi/pull/5373
