### ISSUE TITLE
[Discussion] Branch name guidelines

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#43]
Should we have rules for branch names?

For now I've seen we using:

A) `username/something`
B) `feature-something`
C) `issuenumber-description-extra` (based on GitHub UI _Create a branch for this issue_)

I link the option C as it's easy to read the issue number and also the feature scope. Also can be automatically generated if we start the new feature workflow from the GitHub issue page.

**Comment by hammer** [comment]
cc #2
