### ISSUE TITLE
Implement cheat sheet screen

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#441]

**Comment by cguedes** [comment]
The current design only has content for the first screen/tab/section.

![image](https://github.com/refstudio/refstudio/assets/174127/bfa4b4ee-bd5a-40eb-8879-5983313dbd4a)

We need to decide which tabs we will have and what is the content. 

This is the list of all keyboard shortcuts used by the application:

Ref Studio Keyboard Shortcuts
* Menu → File
    * `⌘ N` - New File (known shortcut)
    * `⌘ S` - Save File (known shortcut)
    * `⌘ W` - Close Editor (known shortcut)

* Menu → Edit
    * These are all standard know, native, shortcuts

* Menu → References
    * `⌘ R` - Open the references editor (our shortcut, normally used to refresh the app)

* Menu → View
    * Toggle Full Screen - Native shortcut. Don’t even know what that globe is!
    * `F11` - Notifications - Toggle the notification drawer (our shortcut)

* Menu → Window
    * `⌘ M` - Native shortcut to minimize the app

* Application
    * `⌘ K` - Open Command Palette (+/- known shortcut)
    * `⌘ P` - Open Files Palette (menu inside the command palette) (shortcut inspired by VSCode)
    * `⌘ 1` - Select / Toggle Visibility of Explorer Pane (our shortcut)
    * `⌘ 2` - Select / Toggle Visibility of References Pane (our shortcut)
    * `⌘ 9` - Select / Toggle Visibility of Rewriter (our shortcut)
    * `⌘ 0` - Select / Toggle Visibility of Chatbot (our shortcut)

* Editor
    * Standard text editor keyboard shortcuts (⌘ B, ⌘ I, ⌫, ⌘ Z, ⌘ ⇧ Z, ...)
    * Standard basic markdown keyboard [shortcuts](https://www.markdownguide.org/cheat-sheet/) (#, ##, ###, *, ...)
    * Text completion (our shortcuts)
        * `⌘ J` - Ask for text completion (when triggered again cycle through choices)
            * `↹`, `→`, `↵` - to accept suggestion
            * `⎋` - (Escape) to remove suggestion
    * References (our shortcuts)
        * `[` - Trigger a references citation interaction (show a popup to select a reference)
            * `@` - Inside a citation will trigger the popup to select a reference)
    * "Notion-like" shortcuts
        * `> {SPACE}` - Creates a collapsible section
            * `⌘ ↵` - Expand/Collapse the collapsible section
        * `↹` - Indent editor block
        * `⇧ ↹` - Remove indent from block
        * `⎋` - Toggle block navigation
            * `↑`/`↓` - Select previous/next block
            * `→` - Expand collapsible section or select first child
            * `←` - Collapse collapsible section or select parent

**Comment by cguedes** [comment]
Will implement the following screen for now, added to PR #546 

<img width="1151" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/ffe7877e-e22e-4fcb-8ab6-0abb7669976a">
