### ISSUE TITLE
Gracefully handle FileNotFound exception if a user tries to view references before any have been ingested

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#444]
After running `yarn python:test` we can see that two new untracked files are created: `does_not_exist.json` and `to_be_mocked.json`.

We should either ignore them or make sure they are removed.

![image](https://github.com/refstudio/refstudio/assets/174127/1d0f28c0-2102-4a47-b02e-293c9eb05f30)

CC @gjreda

**Comment by gjreda** [comment]
@cguedes Where do you see these files getting written? Running `yarn python:test` and then `git status` does not reveal any untracked files.

**Comment by cguedes** [comment]
I see them as you can see in the image. Do you have a global ignore file with them?

<img width="2047" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/7eb9444f-7f2d-451d-9a18-2ca37d230f81">

**Comment by gjreda** [comment]
Running from `main` ...
<img width="921" alt="image" src="https://github.com/refstudio/refstudio/assets/921995/5666c3f3-71f1-4ef4-9ab5-28078b71a297">

Could this be caused by a change you have on your branch?

**Comment by cguedes** [comment]
You are right. Must be something in the branch. I've just tested in main (a322cd07ac40499cc08a4dd2ded329123f50a3db) and I don't see the files!

<img width="2049" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/3a967b7d-8c4a-4ed3-95fd-376890fa3203">


I've now merged #425 into main and now we have this issue in main! 

Can you spot anything weird in the [changed files](https://github.com/refstudio/refstudio/commit/1e2521f17622d29eb02652993be2b7abe88683fd)?

**Comment by gjreda** [comment]
<img width="721" alt="image" src="https://github.com/refstudio/refstudio/assets/921995/5aba3e79-802e-48e8-bcb0-bc90c7c79da9">

That change is causing the files to be created even though the [tests in question](https://github.com/refstudio/refstudio/blob/main/python/tests/test_ingest.py#L324) here are simply trying to mock the object.

I missed that in my review, but I don't think we should automatically be trying to create the file.

**Comment by cguedes** [comment]
Good catch. Would that file be automatically created on the first call? Bc I've had to add this code to prevent an error calling the backend.

**Comment by gjreda** [comment]
As long as ingest has been successfully run, `.storage/references.json` should exist.

**Comment by cguedes** [comment]
The issue is that the app try to get ingested references before any ingestion and that would fail because of this missing file.

**Comment by gjreda** [comment]
Ah, I think I understand the issue. This would come up with the user tries to view references, but there aren't any yet?

If so, I think a simple backend fix is just gracefully handling a `FileNotFound` exception for this particular call, rather than generating the files no matter what.

**Comment by cguedes** [comment]
Exactly. Ok, I think that that would work.
