### ISSUE TITLE
Improve projects API and stop depending on Tauri FS types

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#448]
The API output for the `/api/projects` (list projects) and `/api/projects/{id}` (project details) should improve to:

- not use full paths (the project path) bc it can be a security concern
- use a tree output for the project filesystem instead of a flat list of filepaths
- make sure we ignore know files (ex: .staging)
- adopt an output type compatible (close match) to `FileEntry.ts` instead of the `FileEntry` from `@tauri-apps/api/fs`

After these changes we should be able to update the client code to remove `convertTauriFileEntryToFileEntry`

This is related to #414 and a follow-up of #425.

**Comment by gjreda** [comment]
@danvk @cguedes How about this for the response from project details? I'll also hide anything prefixed with `.`
```
{'.': ['web.py',
       '.coverage',
       'api.schema.json',
       'cli.schema.json',
       'README.md',
       'generate_schema.py',
       'main.py'],
 '.pytest_cache': ['CACHEDIR.TAG', 'README.md', '.gitignore'],
 '.pytest_cache/v/cache': ['nodeids', 'lastfailed', 'stepwise'],
 'sidecar': ['ingest.py',
             '__init__.py',
             'prompts.py',
             'shared.py',
             'chat.py',
             'cli.py',
             'http.py',
             'storage.py',
             'ranker.py',
             'settings.py',
             'search.py',
             'projects.py',
             'typing.py',
             'rewrite.py',
             'stopwords.py'],
 'tests': ['test_shared.py',
           'conftest.py',
           'test_ranker.py',
           'test_search.py',
           'test_prompts.py',
           '__init__.py',
           'test_storage.py',
           'test_ingest.py',
           'test_http.py',
           'test_projects.py',
           'test_chat.py',
           'test_rewrite.py',
           'test_settings.py'],
 'tests/fixtures': ['.DS_Store'],
 'tests/fixtures/data': ['references.json'],
 'tests/fixtures/pdf': ['test.pdf', 'grobid-fails.pdf'],
 'tests/fixtures/text': ['chicago.txt', 'baseball.txt'],
 'tests/fixtures/xml': ['grobid-fails_500.txt', 'test.tei.xml']}
```

**Comment by cguedes** [comment]
I think that the server should be able to specify the sort order for directories and files (ex: in the root), so we shouldn't use hash.

I thought something like this to close match what we currently have for the `FileEntry`. We can drop `isFile` and use the undefined `children` to detect if the entry is a file or folder.

What do you think of this @danvk @sehyod ?

```json
{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "project_name",
  "path": "project_path", // for now this should still be the full path of the project as we depend on this for the open project feature
  "contents": [
    {
        "name": "exports",
        "path": "exports",
        "chidren":[
            // Empty folder
        ]
    },
    {
      "name": "uploads",
      "path": "uploads",
      "chidren": [
        {
          "isFile": true,
          "name": "file1.pdf",
          "path": "uploads/file1.pdf"
        },
        {
          "isFile": true,
          "name": "file2.pdf",
          "path": "uploads/file2.pdf",
        },
        {
          "isFile": true,
          "name": "file3.pdf",
          "path": "uploads/file3.pdf",
        }
      ]
    },
    {
      "isFile": true,
      "name": "Cover.refstudio",
      "path": "Cover.refstudio"
    },
    {
        "isFile": true,
        "name": "Abstract.refstudio",
        "path": "Abstract.refstudio"
      }
  ]
}
```
```

**Comment by sehyod** [comment]
The sorting logic currently lives in the file entries atom (`src/atoms/core/fileExplorerEntry.ts`), so it's fine if the backend does not sort them. We could remove this logic from the frontend but it means we would have to wait for the backend response to update the file explorer when doing actions like renaming a file.

As for the response type, I like what you suggested, basically the same as our `FileExplorerEntry` type without the atoms. I don't mind using `children` to determine whether the entry is a file or not
