### ISSUE TITLE
Set up frontend testing

### ISSUE THREAD

**Issue by danvk** [refstudio/refstudio#45]
Splitting this off from #10. @hammer would like 100% test coverage (nice round number). We're currently at zero.

Jest is the standard choice for any sort of unit test. [React Testing Library](https://github.com/testing-library/react-testing-library) is also the standard choice for testing React components and their interactions, though I'm open to alternatives here. Stubbing out Tauri interactions may be an issue.

End-to-end testing is also an interesting question but probably overkill for now. Playwright and Storybook are the tools I know about in that space.

**Comment by cguedes** [comment]
After some [investigation](https://blog.logrocket.com/testing-vite-minimal-config-using-vitest/), found that [vitest](https://vitest.dev/) is a good solution to unit test Vite projects. It is compatible with Jest and reuse Vite's config, transformers, resolvers, and plugins.

The support for coverage is also built-in with c8.
