### ISSUE TITLE
Export References behaviour for web

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#456]
In desktop the action "Export References" (accessible via icon in the references sidebar) uses a Tauri dialog to ask for the export file name and location (defaults to /exports/references.bib inside the project).

For the web, we need to choose the desired behaviour taking into consideration what was choose for #455.

My considerations:
1. We should also add this action to the menu (desktop) and command palette (both)
2. We can follow a similar approach to what I propose in #455 a direct export (no dialog) to the project folder structure at `/exports/references.bib`.

----

This is a follow-up after https://github.com/refstudio/refstudio/pull/425

**Comment by hammer** [comment]
I'm fine with the similar approach as to #455!
