### ISSUE TITLE
Left indent seems too large for wide screens

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#482]
The left indent of a document should be fixed; instead, it seems to vary with the width of the screen. On my laptop screen, when Ref Studio has the whole screen, this left indent position seems overly indented.

<img width="1359" alt="Screenshot 2023-09-04 at 2 22 18 PM" src="https://github.com/refstudio/refstudio/assets/15233/822a762e-e7f7-41d0-b5f6-405d6f796acc">

https://github.com/refstudio/refstudio/assets/15233/6d51a8fc-9047-4027-a1e3-4b80dde54aca

**Comment by hammer** [comment]
Weird, my Google Docs is different! It grays out the area around the writing area so that the left indent is always constant within the writing area. I wonder how you're getting a view with the writing area always white?

https://github.com/refstudio/refstudio/assets/15233/f7d6d076-7634-4410-b26c-991bf409039e

I guess at some point we should float the toolbar with formatting actions (as Notion does) and have the active writing area be fixed width but somehow distinguished from the rest of the large white writing area.

I think ours looks weird because we have the background behind the writing area, and the left indent area should be part of the background, not part of the writing area.

**Comment by sehyod** [comment]
Yes, sorry I wasn't specific enough: my video was Google Docs in the pageless layout.

I will share your feedback with the design team and see what they think. I think the issue we currently have is the toolbar: if we make the left indent part of the background it means the toolbar should start after the left indent too, and this means the toolbar would look a bit small

https://github.com/refstudio/refstudio/assets/58954208/a31bd974-5fae-4fae-8302-4423e2492237
