### ISSUE TITLE
Remove embedding creation from PDF ingestion

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#50]
We want to populate the ReferenceView with metadata once the uploaded references have been parsed: https://github.com/refstudio/refstudio/issues/49

As currently constructed, Reference metadata is not returned until the entire pipeline runs. However, metadata is available as json fairly early on in the pipeline.

Separating embedding creation from the rest of the ingestion pipeline would allow us to return the metadata response sooner and allow things to feel snappier.

**Comment by hammer** [comment]
Definitely a good idea, we may not end up creating embeddings at all depending on how our AI interactions evolve.

**Comment by gjreda** [comment]
Since we are using OpenAI for chat and rewrite modeling, I'll also explore using their embeddings API as part of this issue. This would allow us to remove `sentence-transformers` and thus `torch`. These two libraries increase the complexity and size of the binary, resulting in it being much slower.

**Comment by gjreda** [comment]
I am going to entirely remove embeddings creation for now and will revisit it as part of #82, when we might actually want embeddings.

Inclusion of `sentence-transformers` and its dependencies are resulting in a lot of complexity and causing downstream issues that we do not need to block on right now:
- `torch` dependencies are [causing CI/CD issues](https://github.com/refstudio/refstudio/actions/runs/5153570286/jobs/9280984530#step:4:113)
- The underlying `dylib` and `so` files [make packaging the binary for the sidecar difficult](https://github.com/refstudio/refstudio/issues/56)
