### ISSUE TITLE
Release 23.2.0

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#540]
Let's aim for a release on Tuesday, September 19. @cguedes could you lead the release process, and write a "How to Release" document that others can follow in the future?

**Comment by gjreda** [comment]
@hammer I suspect we'll be able to get #541 in there too cc @cguedes

**Comment by jvoytek** [comment]
It's not impossible that [#138] could be included in the release but I wouldn't count on it. I should have a design to show at the meeting tomorrow morning, maybe we'll have a better idea then.
