### ISSUE TITLE
Add endpoint(s) for adding a new reference from S2 search results

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#548]
This is at least two endpoints:
1. Takes a url to a pdf and downloads the pdf to a projects `uploads`. Possibly calls some ingest related functions (e.g. chunk reference).
2. Takes the metadata from S2 and updates the reference json storage accordingly

              Image preview for reference...
![Screenshot 2023-09-13 at 11 39 55 AM](https://github.com/refstudio/refstudio/assets/8864493/347938cb-ab85-4ec3-a95c-4f64e673c2cc)
![Screenshot 2023-09-13 at 11 41 47 AM](https://github.com/refstudio/refstudio/assets/8864493/e374a3bc-6f1a-4b40-b5b8-8542867bf9af)

_Originally posted by @jvoytek in https://github.com/refstudio/refstudio/issues/138#issuecomment-1718140352_

**Comment by hammer** [comment]
🤔 this `create_from_url` method could also support allowing users to just add references from an arbitrary URL at some point...

**Comment by cguedes** [comment]
Another solution would be to post to `/references/{project_id}` with multiple payloads (i.e. ways of ingest). For me that would be the best approach. You would have a base type with a discriminator type field and we would implement:

```json
{
    "type": "ingest-uploads"
}
```

and
```json
{
    "type": "ingest-s2",
    // payload with metadata (maybe the s2 endpoint response)
}
```

**Comment by jvoytek** [comment]
One async request would be better than two

**Comment by gjreda** [comment]
> 🤔 this create_from_url method could also support allowing users to just add references from an arbitrary URL at some point...

That's how I think about it too, though the long tail of this could be quite long. Even just testing some of the results from S2, it doesn't seem to always be a link directly to the PDF, and sometimes the linked PDF is corrupted in some way.

To your point though, I'm thinking about this endpoint as being more broad than just S2, since it should work for any direct-to-pdf-url (though ideally we'd have a way of getting some metadata without running grobid, like we can with S2).
