### ISSUE TITLE
Ollama doesn't work at all, I also get an error ('async for' requires an object with aiter method, got ModelResponse)

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#569]

**Comment by gjreda** [comment]
Changing the underlying call here to be async using `litellm.acompletion` results in things working for OpenAI, but still some issues for Ollama.

```python
  File "/Users/greg/Dropbox/refstudio/python/sidecar/ai/scratch.py", line 26, in ask_question
    response = await litellm.acompletion(**params)
  File "/Users/greg/Library/Caches/pypoetry/virtualenvs/refstudio-iTeERiwC-py3.10/lib/python3.10/site-packages/litellm/main.py", line 90, in acompletion
    return(
TypeError: 'async for' requires an object with __aiter__ method, got generator
```

[Following up with the litellm team](https://discord.com/channels/1123360753068540065/1154457620770472058) in their discord and they were also able to reproduce the issue. They've very helpfully [pushed a fix](https://github.com/BerriAI/litellm/commit/35bb6f5a508437e59c18e656c60f71c5c29c92ce), though it hasn't yet been released.

**Comment by cguedes** [comment]
given how frequent they push, we should be able to install the new version soon.
