### ISSUE TITLE
Python client for AI interactions

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#58]
We've talked a bit about choosing a Python client that can be used across LLM APIs, as well as potential abstractions for working with prompt templates and prompt chains. It's probably time to take those conversations from Notion and Slack to GitHub!

A big list of prompt engineering tools is at https://www.promptingguide.ai/tools. I don't think we need to explore all of them of course. Many tools belong to more than one of these categories, but I think it's useful to break them down a bit.

### Client libraries
These are libraries that provide a common Python interface to multiple LLM backends.

- LangChain's [Models](https://python.langchain.com/en/latest/modules/models.html)
- LlamaIndex's [LLM](https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/root.html)
- https://github.com/r2d4/openlm
- https://github.com/danielgross/python-llm
- https://github.com/kagisearch/pyllms

### Prompt templates
These are libraries that make working with complex prompts easier, usually using some template library like Jinja or Handlebars.

- LangChain's [Prompts](https://python.langchain.com/en/latest/modules/prompts.html)
- https://github.com/microsoft/guidance
- https://github.com/HazyResearch/manifest

### Call trees
These are libraries that make it easier organize and execute a collection of calls to LLM and potentially other APIs (often vector databases) necessary to solve a high-level task. It would probably be better to break this group up to separate indexing and memory APIs from call tree APIs...

- LangChain's [Chains](https://python.langchain.com/en/latest/modules/chains.html)
- https://github.com/srush/MiniChain
- https://github.com/jerryjliu/llama_index
- https://github.com/eth-sri/lmql
- https://github.com/stanfordnlp/dsp

**Comment by hammer** [comment]
Nice work not yet in a separate library https://twitter.com/gneubig/status/1663544322233606148

**Comment by hammer** [comment]
https://github.com/deepset-ai/prompthub for prompt management

**Comment by hammer** [comment]
https://github.com/hegelai/prompttools

**Comment by hammer** [comment]
https://github.com/microsoft/Typechat for typed prompt building in TypeScript

**Comment by hammer** [comment]
https://github.com/philschmid/easyllm another client library

**Comment by hammer** [comment]
https://github.com/BerriAI/litellm another client library

**Comment by hammer** [comment]
There's a fourth category I suppose for controlling output.

### Controlling output
- https://github.com/1rgs/jsonformer
- https://github.com/ShreyaR/guardrails
- https://github.com/normal-computing/outlines
- https://github.com/jxnl/instructor
- https://github.com/r2d4/rellm
- https://github.com/ggerganov/llama.cpp/pull/1773
- https://github.com/huggingface/transformers/issues/24536

**Comment by hammer** [comment]
Another one https://github.com/zhudotexe/kani

Given our `litellm` issues we may want to reopen this issue, or I suppose file another...

**Comment by ghost** [comment]
hey @hammer what issues are you facing with litellm? I'd like to make sure we're stable for y'all in prod. 

Also happy to set up a dedicated support channel for y'all. 

Here's my number: +17708783106. 

Here's our discord: [![Chat on Discord](https://img.shields.io/static/v1?label=Chat%20on&message=Discord&color=blue&logo=Discord&style=flat-square)](https://discord.gg/wuPM9dRgDw)
