### ISSUE TITLE
Editor polish

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#584]
While trying out the new release I found several rough edges on the Editor that would be nice to smooth over. I'll file separate issues for each and link them below.

- [x] https://github.com/refstudio/refstudio/issues/585
- [x] https://github.com/refstudio/refstudio/issues/586
- [x] https://github.com/refstudio/refstudio/issues/587
- [x] https://github.com/refstudio/refstudio/issues/588

**Comment by cguedes** [comment]
Closing as all features are merged into main, and [release 23.2.1](https://github.com/refstudio/refstudio/releases/tag/23.2.1).

We also created the follow-up issue #595 to improve #587.
