### ISSUE TITLE
List text should indent when wrapped

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#585]
Notion indents the whole text when the block is converted to any kind of list:

https://github.com/refstudio/refstudio/assets/15233/e17ded36-1276-4227-ab9a-a63595e172a2

Ref Studio only indents the first line of text:

https://github.com/refstudio/refstudio/assets/15233/f17e4af1-c11e-4492-ba5e-056e5b126675

There's also some weird cursor behavior for Ref Studio you might catch in the video in which, after deleting the list bullet, the cursor briefly appears to be 2 characters to the right of the beginning of the line, then resets back to the beginning of the line.

**Comment by sehyod** [comment]
I think the cursor behavior is a webkit issue: it does not occur in the web app (in Chrome), while it consistently occurs in the desktop app on MacOS.


https://github.com/refstudio/refstudio/assets/58954208/9a8bde4b-9275-4714-9452-7d9506b30f17

Unfortunately I don't think there is anything we can do about it
