### ISSUE TITLE
Minimum Lovable Product

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#6]
Our MVP should have:

1. Writing: WYSIWYG Markdown editor.
2. References: build a reference list with S2 APIs.
3. AI interactions: send content to a foundation model and get a response.

These 3 components should talk to each other:
1 -> 2: references know where they are cited.
1 -> 3: editor content can be sent to the AI.
2 -> 1: editor can cite references.
2 -> 3: reference content available to the AI.
3 -> 1: AI can make changes to the editor.
3 -> 2: AI can edit reference list (e.g. suggest a reference).

**Comment by gjreda** [comment]
@hammer Given point 2 above, is it fair to assume the fully local use case (no internet) is out of scope for v1?

I think that scope decision has implications on backend design in terms of the LLM we use, any database or vector storage, etc.

**Comment by hammer** [comment]
@gjreda I wouldn't take these issues to be written in stone. I just wrote something up to start discussion. I would like to keep local mode high on the priority list for this 3 month work cycle, which may go beyond an MVP. Upon further thought it's probably easier to bring your own (BYO) PDF than to talk to S2 APIs, so perhaps point 2 should be BYO PDF instead of use of S2 APIs, which involves a second step of fetching the full text.

**Comment by hammer** [comment]
Thank you @danvk for the title improvement from `Viable` to `Lovable` 😑

**Comment by gjreda** [comment]
@hammer just came across this one. I'm going to close it feels like we've finished the pieces mentioned here, but feel free to reopen if you want to keep it around
