### ISSUE TITLE
AI interactions: rewrite

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#60]
Some operations on a span or selection:

- Change tone (e.g. casual, formal)
- Change length
- Change tense
- Change form

[RewriteLM: An Instruction-Tuned Large Language Model for Text Rewriting](https://arxiv.org/abs/2305.15685) (2023) is a recent Google paper that proposes a benchmark, OpenRewriteEval, that has some useful examples.

**Comment by gjreda** [comment]
Pulling over relevant API design notes from #19 

### Span Operation: Rewrite a highlighted block of text (concisely)

**Action**:
- User highlights block of text and there is some UX component that allows them to ask for the text to be rewritten in a more concise manner.
- There will likely be other types of "rewrite" operations beyond just conciseness, but conciseness can be a starting point.
- UX for this is TBD

**Input**:
- Highlighted span of text (for now ... I can imagine the prior blocks of text or entire document would also be useful here)

**Sidecar Response**:
- json, list of candidate rewrites

Example Response:
```json
[
  {
    "id": 1,
    "text": "I'm a paragraph"
  },
  {
    "id": 2,
    "text": "I'm an another option"
  }
]
```
