### ISSUE TITLE
PDF ingest does not work properly with non-scholarly documents

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#79]
- https://ref-studio.slack.com/archives/C05525DV9HN/p1685694897585369?thread_ts=1685633929.177849&cid=C05525DV9HN

From @sehyod 

> I did some testing this morning and it appears there is indeed an issue with one of the pdfs I had in my directory. I'm joining the pdf to this message but it's not a scholar pdf, just a text pdf I used while working on the PDF viewer.

Since it is not a scholarly PDF, I suspect that grobid is unable to parse it and then downstream processing within `ingest.py` is not handling that properly.

**Comment by sehyod** [comment]
To give more context, the pdf I was using was a lorem-ipsum pdf, containing only text. I think the file has been created with Word, this may be where the issue come from.
When running the ingestion, the sidecar doesn't return anything (the stdout is empty) and the error trace is the following:
```
Traceback (most recent call last): (filesystem.tsx, line 52)
  File "main.py", line 48, in <module>
  File "sidecar/ingest.py", line 245, in main
  File "sidecar/ingest.py", line 53, in run
  File "sidecar/ingest.py", line 232, in create_and_persist_embeddings
  File "lancedb/db.py", line 97, in create_table
  File "lancedb/table.py", line 216, in create
  File "lancedb/table.py", line 36, in _sanitize_data
  File "lancedb/table.py", line 242, in _sanitize_schema
  File "lancedb/table.py", line 256, in _sanitize_vector_column
ValueError: 'vector' is not in list
[85999] Failed to execute script 'main' due to unhandled exception!
usage: main [-h] [--debug] {ingest,ai} ...
main: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(23)' (choose from 'ingest', 'ai')
```

**Comment by gjreda** [comment]
Some more notes from Slack:
> Yes, I am starting with a clean directory (I have run the reset_uploads script), I upload a "regular" PDF (Hidden technical debt...) and when I log the stderr in the runPDFIngestion function, here is the result:
usage: main [-h] [--debug] {ingest,ai} ... (filesystem.tsx, line 52)
main: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(23)' (choose from 'ingest', 'ai')

> But everything else is working as expected and I do get the correct stdout. So if I hadn't been logging the stdout I wouldn't have noticed there was an issue (edited)

**Comment by sehyod** [comment]
I have tried locally with this file and I logged the stdout after the python binary has been called. Here is the result:
```Processing of /Users/mathis/Library/Application Support/com.tauri.dev/project-x/uploads/FActScore-.Fine-grained.Atomic.Evaluation.of.Factual.Precision.in.Long.Form.Text.Generation.pdf failed with error 500 , [GENERAL] An exception occurred while running Grobid.
{"project_name": "project-x", "references": []}```
So grobid does return an empty list of references, skipping the "invalid file", as we would expect, but because the error message from grobid is also printed to the stdout, the frontend cannot parse the response.

**Comment by gjreda** [comment]
Spent some time debugging this.

The Grobid server likes to print out its own log messages (e.g. `"Server connection is alive"`), rather than returning http status codes or raising exceptions. These log messages wind up on stdout, which causes issues with the sidecar and is why we use [`HiddenPrints` here](https://github.com/refstudio/refstudio/blob/main/python/sidecar/ingest.py#L81). In this case, it prints out the exception on the next line, at `client.process`, so it's just a matter of also wrapping that in `HiddenPrints`.

If Grobid is unable to process a PDF, it will still create a file for it in the output directory, however it will be named differently (in this case, `FActScore-.Fine-grained.Atomic.Evaluation.of.Factual.Precision.in.Long.Form.Text.Generation_500.txt`). Unfortunately, the contents of this file give no indication of why Grobid was unable to parse the document.

```bash
~/Library/Application Support/com.tauri.dev/project-x
❯ cat .grobid/FActScore-.Fine-grained.Atomic.Evaluation.of.Factual.Precision.in.Long.Form.Text.Generation_500.txt
[GENERAL] An exception occurred while running Grobid.
```

I think there are two immediate fixes:
1. Don't allow the Grobid server to print to stdout if there's a problem.
2. Update the JSON response from PDF ingestion to include references that Grobid was unable to process, so that we can inform the user in some way.

But I think there's a broader question about how we want to handle references that Grobid is unable to parse. Some ideas:
1. Display something in the UI so that the user knows we were unable extract reference metadata. Unfortunately, given Grobid's lack of error details, I don't think we can tell the user much about _why_ metadata couldn't be extracted.
3. For the problematic reference, allow the user to manually enter metadata. Probably a nice to have long-term.
4. Naively extract the full text of the reference using a library like [pdfplumber](https://github.com/jsvine/pdfplumber). We probably can't get nicely structured metadata without a good amount of work, but even just extracting the full raw text of the document will still allow us to interact with it in `chat`.

**Comment by gjreda** [comment]
Filed a [Grobid issue](https://github.com/kermitt2/grobid/issues/1024) with @hammer's example PDF. I'm hoping to get a better understanding of why this particular PDF is problematic so that we can watch out for similar ones.
