### ISSUE TITLE
Configure codecov.io

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#89]

**Comment by sergioramos** [comment]
I tried (in multiple ways) and can't get this repo to show up on Codecov dashboard 😔 Might have to be @hammer as he is the org owner.

**Comment by hammer** [comment]
I read through a recent [blog post](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/) from Codecov and it seems like someone has to send a request for Codecov to be installed for this organization. I have looked everywhere and can't figure out how to generate this request...

**Comment by hammer** [comment]
Hmm okay I think I did it. I still don't see any repos from this org on Codecov.io but I do see the Codecov app installed on GitHub...

**Comment by hammer** [comment]
Okay I finally got this repo to show up on Codecov.io! I've added our repository token as repository secret, so step 2 is for y'all to add this to our Actions yaml file someplace:

```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
   env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

**Comment by cguedes** [comment]
@sehyod please add these
